//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_UTPEntities : DbContext
    {
        public DB_UTPEntities()
            : base("name=DB_UTPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ALUMNO> TBL_ALUMNO { get; set; }
        public virtual DbSet<TBL_CURSO> TBL_CURSO { get; set; }
        public virtual DbSet<TBL_NOTA> TBL_NOTA { get; set; }
    }
}
