//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CURSO
    {
        public int INT_CURSOID { get; set; }
        public string VCH_NOMBRE { get; set; }
        public Nullable<bool> BIT_ESTADO { get; set; }
        public Nullable<System.DateTime> DAT_FECHA_CREA { get; set; }
        public Nullable<System.DateTime> DAT_FECA_ACT { get; set; }
        public Nullable<int> INT_USU_CREA { get; set; }
        public Nullable<int> INT_USU_ACT { get; set; }
    }
}
